# Generated by Django 4.2.5 on 2024-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_choice_text_choice_text'),
        ('accounts', '0002_customuser_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exam',
            field=models.ManyToManyField(to='exams.exam'),
        ),
    ]
