# Generated by Django 4.2.5 on 2025-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_exam_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_paid',
            new_name='legacy_has_paid_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_paid_v2',
            field=models.BooleanField(default=False),
        ),
    ]
