# Generated by Django 4.2.5 on 2024-01-21 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_userexamprogress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExamProgress',
            new_name='UserExamState',
        ),
        migrations.CreateModel(
            name='UserExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_exam_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.userexamstate')),
            ],
        ),
    ]
