# Generated by Django 4.2.5 on 2024-02-10 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamstate',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
