# Generated by Django 4.2.5 on 2024-02-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_userexamstate_time_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
