# Generated by Django 4.2.5 on 2024-01-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_userexamprogress_userexamstate_userexamanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exams.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exams.choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='answers',
            field=models.ManyToManyField(through='exams.UserAnswer', to='exams.question'),
        ),
    ]
