# Generated by Django 4.2.5 on 2024-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_category_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
