# Generated by Django 4.2.5 on 2024-01-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_useranswer_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question_text',
        ),
    ]
