# Generated by Django 4.2.5 on 2025-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_active_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
