# Generated by Django 4.2.5 on 2024-01-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_useranswer_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswer',
            new_name='UserExamAnswer',
        ),
    ]
