# Generated by Django 4.2.5 on 2024-01-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_useranswer_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='choice_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='exam_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='num_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexamstate',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
