# Generated by Django 4.2.5 on 2025-04-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
