# Generated by Django 4.2.5 on 2024-01-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_rename_useranswer_userexamanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExamAnswer',
            new_name='UserAnswer',
        ),
    ]
