# Generated by Django 4.2.5 on 2025-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
