# Generated by Django 4.2.5 on 2024-01-21 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_rename_userexamanswer_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
