# Generated by Django 4.2.5 on 2025-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='predicted_score_file',
            field=models.FileField(blank=True, null=True, upload_to='predicted_scores/'),
        ),
    ]
