# Generated by Django 4.2.5 on 2024-11-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='stats',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_count',
            field=models.IntegerField(default=0),
        ),
    ]
