# Generated by Django 4.2.5 on 2024-12-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_active_exam_is_active'),
        ('review', '0002_remove_quiz_stats_answer_choice_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.category'),
        ),
    ]
