# Generated by Django 4.2.5 on 2025-01-14 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_alter_explanation_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquizstate',
            unique_together={('user', 'quiz')},
        ),
    ]
