# Generated by Django 4.2.5 on 2024-12-22 22:21

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='explanation',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_title_snapshot',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=models.SET(review.models.get_sentinel_quiz), to='review.quiz'),
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.question')),
            ],
        ),
    ]
