# Generated by Django 4.2.5 on 2025-01-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_question_quiz_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userquizanswer',
            unique_together={('user_quiz_state', 'question')},
        ),
    ]
