# Generated by Django 4.2.5 on 2025-01-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_active_exam_is_active'),
        ('review', '0005_alter_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.category'),
        ),
    ]
