# Generated by Django 4.2.5 on 2025-01-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_active_exam_is_active'),
        ('review', '0006_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='exams.examtype'),
        ),
    ]
