# Generated by Django 4.2.5 on 2025-01-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_quiz_category_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizstate',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.quiz'),
        ),
    ]
