# Generated by Django 4.2.5 on 2025-02-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_question_flag_count_question_flagged_questionflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionflag',
            options={'verbose_name': 'Flagged Question', 'verbose_name_plural': 'Flagged Questions'},
        ),
        migrations.AddField(
            model_name='questionflag',
            name='reason_expanded',
            field=models.TextField(blank=True, null=True),
        ),
    ]
