# Generated by Django 4.2.5 on 2025-02-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_alter_questionflag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionflag',
            old_name='reason_expanded',
            new_name='reason_explained',
        ),
    ]
