# Generated by Django 4.2.5 on 2025-07-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_rename_reason_expanded_questionflag_reason_explained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='flag_count',
        ),
        migrations.AddField(
            model_name='question',
            name='flag_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='QuestionFlag',
        ),
    ]
