# Generated by Django 4.2.5 on 2025-12-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_remove_question_flag_count_question_flag_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
